### ISSUE TITLE
Error while attempting to login

### ISSUE THREAD

**Issue by Double0negative** [DoctorMcKay/node-steam-user#104]
Attempting to login throws an error with the following code (using 3.19.1)
```java

var SteamUser = require('steam-user'); 
var client = new SteamUser();

client.logOn({
	"accountName": "user",
	"password": "pass"
});
```

```
events.js:307
    throw new TypeError('"listener" argument must be a function');
    ^

TypeError: "listener" argument must be a function
    at TCPConnection.once (events.js:307:11)
    at TCPConnection.Socket.connect (net.js:943:10)
    at CMClient.connect (/home/drew/programming/steam/bot/node_modules/steam-client/lib/cm_client.js:132:19)
    at gotCMList (/home/drew/programming/steam/bot/node_modules/steam-user/components/logon.js:171:17)
    at /home/drew/programming/steam/bot/node_modules/steam-user/components/logon.js:132:6
    at Gunzip.<anonymous> (/home/drew/programming/steam/bot/node_modules/steam-user/components/webapi.js:84:4)
    at emitNone (events.js:91:20)
    at Gunzip.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
```

**Comment by DoctorMcKay** [comment]
Show all your code.

**Comment by Double0negative** [comment]
This is the entire code.

**Comment by DoctorMcKay** [comment]
What version of node do you have?

**Comment by Double0negative** [comment]
```
$ node --version
v7.7.2
```

**Comment by DoctorMcKay** [comment]
I can't reproduce. Also, how exactly do you plan to do anything useful without at least handling `loggedOn`?

**Comment by Double0negative** [comment]
I haven't got to doing anything more complicated because I can't get the first step to work. I have also tried using the BasicBot Example and get the same error. Are there any dependencies or anything that needs to be installed prior to using this?

**Comment by DoctorMcKay** [comment]
No, you don't need anything besides Node.js and the dependencies that npm installed for you. Please move this to the [forum](https://dev.doctormckay.com) as the issue tracker is for bugs in the module.

**Comment by Double0negative** [comment]
OK, for future reference this was actually a bug in node 7.7.2 https://github.com/tediousjs/tedious/issues/532, upgrading fixes the issue.
