### ISSUE TITLE
Error after updating steam-user

### ISSUE THREAD

**Issue by shadypollen** [DoctorMcKay/node-steam-user#111]
I updated steam user using `npm update steam-user` and now I'm getting this error when trying to run the script:

```
let g_StartupTimestamp = Math.floor(Date.now() / 1000);
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/aleks/Documents/Programming/Javascript/tf2_bot/node_modules/steam-user/index.js:1:63)
    at Module._compile (module.js:410:26)

```

**Comment by Psycho345** [comment]
Update your node version.

**Comment by shadypollen** [comment]
Works now, thanks!

**Comment by DoctorMcKay** [comment]
I'm pretty shocked that anything was working for you on a node version older than v4. I'll add a note to package.json that this version (v3) requires 4.0.0 or later. I'm planning on a major release (v4) which requires node 6 or later in the not-so-distant future.

**Comment by shadypollen** [comment]
@DoctorMcKay heh, I decided to get back to bot-scripting after a long hiatus, that's why everything was so outdated
