### ISSUE TITLE
throw new Error("Already logged on, cannot log on again")

### ISSUE THREAD

**Issue by alicrypto** [DoctorMcKay/node-steam-user#117]
Why do I get an error?
throw new Error("Already logged on, cannot log on again");
                ^

Error: Already logged on, cannot log on again
    at SteamUser.logOn (C:\Users\admin\Desktop\steambot\node_modules\steam-user\components\logon.js:11:9)
    at Timeout._onTimeout (C:\Users\admin\Desktop\steambot\node_modules\steam-user\components\logon.js:420:10)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)

Code:
```
// packages
const steamUser = require('steam-user'),
      randomString = require("randomstring"),
      fs = require('fs'),
      md5 = require('md5'),
      request = require('request');
//

// global variables
var bot = {
    login: randomString.generate(10),
    password: randomString.generate(10),
    email: randomString.generate(6),
    isCreate: false
}
var client = new steamUser();
//

client.logOn();
console.log('Connecting to Steam...');

client.on('loggedOn', () => {
    if (!bot.isCreate) {
        console.log('Successful connection!');
        console.log('Creating new Steam Bot...');
        console.log('Generated login: ' + bot.login);
        console.log('Generated password: ' + bot.password);
        console.log('Generate email...');

        request('http://post-shift.ru/api.php?action=new&name=' + bot.email + '&type=json', (error, response, body) => {
            data = JSON.parse(body);
            if (!data.error) {
                console.log('Email ' + data.email + ' is generated.');
                client.createAccount(bot.login, bot.password, data.email, (status, steamid) => {
                    if (status == 1) {
                        console.log('Account successfully created.');
                        var info = {
                            login: bot.login,
                            password: bot.password,
                            email: data.email
                        }
                        fs.writeFile('bot.account', JSON.stringify(info), (err) => {
                            if (err) throw err;
                        });
                        client.logOff();
                        console.log('Reconnecting to Steam...');
                        bot.isCreate = true;
                    } else {
                        console.log('ERROR: ' + steamUser.EResult[status]);
                    }       
                });
            } else {
                throw 'EMAIL_ERROR: ' + data.error;
            }
        });
    }
});

client.on('disconnected', () => {
    if (bot.isCreate) {
        var logOnOptions = {
            accountName: bot.login,
            password: bot.password
        }
        client.logOn(logOnOptions);
        console.log('Reconnecting success!');
        client.setPersona(steamUser.Steam.EPersonaState.Online);
	    client.gamesPlayed(440);
    }
});
```

**Comment by Qasde** [comment]
rly make you think 🤔

**Comment by alicrypto** [comment]
@Qasde answer me, pls.

**Comment by Rob--** [comment]
@alicrypto no one is going to answer you, the answer is there in perfect English.
