### ISSUE TITLE
GenerateAuthCode error

### ISSUE THREAD

**Issue by Wolfleader101** [DoctorMcKay/node-steam-user#154]
Hello,
i am getting the following error
```/home/pi/Desktop/Steam-Bot/node_modules/steam-totp/index.js:28
                        let code = exports.generateAuthCode(secret, offset);
                        ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet sup          ported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/pi/Desktop/Steam-Bot/main.js:3:19)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

**Comment by Aareksio** [comment]
Update node

**Comment by andrewda** [comment]
👆 To at least `v8.9.x` or `v9.4.x`, get it from https://nodejs.org/en/

**Comment by Wolfleader101** [comment]
i am using rapsberry pi

**Comment by DoctorMcKay** [comment]
So? Update.

**Comment by Wolfleader101** [comment]
its weird why i cant just do sudo apt-get install nodejs and give me the latest version. same with npm. anyways thanks.

**Comment by DoctorMcKay** [comment]
Repos shipped with the OS often contain outdated software. Google will tell you how you can update.
