### ISSUE TITLE
Path must be string. Received undefined

### ISSUE THREAD

**Issue by timvandam** [DoctorMcKay/node-steam-user#176]
Stack Trace:

```
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.join (path.js:489:7)
    at userData (C:\Users\timol\Desktop\myFolder\node_modules\appdirectory\lib\appdirectory.js:16:25)
    at AppDirectory._setTemplates (C:\Users\timol\Desktop\myFolder\node_modules\appdirectory\lib\appdirectory.js:134:34)
    at new AppDirectory (C:\Users\timol\Desktop\myFolder\node_modules\appdirectory\lib\appdirectory.js:129:10)
    at new SteamUser (C:\Users\timol\Desktop\myFolder\node_modules\steam-user\index.js:104:34)
    at my files
```

This is steam-user index.js:104. This was always there, so this is weird. The exact same thing happens in steam-tradeoffer-manager
```
this.options.dataDirectory = (new AppDirectory({
				"appName": "node-steamuser",
				"appAuthor": "doctormckay"
			})).userData();
```

Edit: This only happens when creating a new instance of a class that creates a SteamUser instance in another file. It does not happen when having the class and the instance of the class in the same file. Weird!

**Comment by Aareksio** [comment]
Are you using `cp.fork`?

**Comment by timvandam** [comment]
I'm not. I'm running it straight from the command prompt

**Comment by Aareksio** [comment]
Try fiddling with it and come up with minimal reproduction example. As I hint, I may suggest checking `process.env` keys `APPDATA` and `LOCALAPPDATA`, these are likely missing.

Asked about `cp.fork`, because it seems to remove these.

A good solution may be using `dataDirectory` option ([docs](https://github.com/DoctorMcKay/node-steam-user#datadirectory)), by setting which you disable use of `AppDirectory` module.

**Comment by timvandam** [comment]
Ah, thank you so much! That was very helpful, my first line was 
`process.env = {};`

Thanks!
