### ISSUE TITLE
Event 'appOwnershipCached' not getting Emited. 

### ISSUE THREAD

**Issue by anupkrbid** [DoctorMcKay/node-steam-user#191]
My code

```
const SteamTotp = require('steam-totp');
const SteamUser = require('steam-user');

const client = new SteamUser();

// If enabled, then node-steam-user will internally cache data about all apps and packages that it knows about.
client.enablePicsCache = true;

// An object containing details for this logon
const logOnOptions = {
  accountName: process.env.STEAM_USERNAME,
  password: process.env.STEAM_PASSWORD,
  twoFactorCode: SteamTotp.generateAuthCode(process.env.STEAM_SHARED_SECRET)
};

// Logs onto Steam
client.logOn(logOnOptions);

// Emitted when you're successfully logged into Steam.
client.on('loggedOn', details => {
  console.log('Logged into Steam!');

  // const steamID64 = client.steamID.getSteamID64();

  client.setPersona(SteamUser.Steam.EPersonaState.LookingToTrade);
});

// Emitted once we have all data required in order to determine app ownership. You can now safely call getOwnedApps, ownsApp, getOwnedDepots, and ownsDepot.
// This is only emitted if enablePicsCache is true.
client.on('appOwnershipCached', function() {
  console.log(client.getOwnedApps());
});
```
Can anyone please tell me whats wrong?

My Node and NPM versions
```
anupkrbid@DESKTOP-MG2N75J:/mnt/e/Projects/web/steam-bot$ node -v
v8.11.2
anupkrbid@DESKTOP-MG2N75J:/mnt/e/Projects/web/steam-bot$ npm -v
6.1.0
```

**Comment by anupkrbid** [comment]
Thanks bro. It worked. 
Two more questions 
1> Can I nor set the ```enablePicsCache ``` property like this
```
client.setOptions({
  enablePicsCache: true
});
```
2> The console log ``` console.log(client.getOwnedApps()); ``` returns me an array of 207 appids but I only have two games. Am I calling the wrong method?

**Comment by DoctorMcKay** [comment]
1. Yes, that works.
2. Every Steam account is automatically granted [Steam Sub 0](https://steamdb.info/sub/0/).

**Comment by anupkrbid** [comment]
Thanks For the Reply 
So for the second Question, I need to filter by app types somehow
And Just to let you know tried setOptions
```
client.setOptions({
  enablePicsCache: true
});
```
also tries
```
client.setOptions(enablePicsCache: true);
```
But got this error instead
```
/mnt/e/Projects/web/steam-bot/node_modules/steam-user/components/apps.js:604
        if (this.steamID.type != SteamID.Type.ANON_USER && !this.licenses) {
                         ^

TypeError: Cannot read property 'type' of null
    at SteamUser.getOwnedPackages (/mnt/e/Projects/web/steam-bot/node_modules/steam-user/components/apps.js:604:19)
    at SteamUser._getLicenseInfo (/mnt/e/Projects/web/steam-bot/node_modules/steam-user/components/apps.js:461:24)
    at SteamUser.setOption (/mnt/e/Projects/web/steam-bot/node_modules/steam-user/index.js:154:9)
    at SteamUser.setOptions (/mnt/e/Projects/web/steam-bot/node_modules/steam-user/index.js:169:8)
    at Object.<anonymous> (/mnt/e/Projects/web/steam-bot/bot.js:7:8)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

**Comment by DoctorMcKay** [comment]
Don't use `setOptions` before being logged on.

**Comment by anupkrbid** [comment]
ok. cool. 
I moved the ```setOptions``` to the ```loggedOn``` Event Callback But got this error
```
Logged into Steam!
/mnt/e/Projects/web/steam-bot/node_modules/steam-user/components/apps.js:605
                throw new Error("We don't have our license list yet.");
                ^

Error: We don't have our license list yet.
    at SteamUser.getOwnedPackages (/mnt/e/Projects/web/steam-bot/node_modules/steam-user/components/apps.js:605:9)
    at SteamUser._getLicenseInfo (/mnt/e/Projects/web/steam-bot/node_modules/steam-user/components/apps.js:461:24)
    at SteamUser.setOption (/mnt/e/Projects/web/steam-bot/node_modules/steam-user/index.js:154:9)
    at SteamUser.setOptions (/mnt/e/Projects/web/steam-bot/node_modules/steam-user/index.js:169:8)
    at SteamUser.client.on.details (/mnt/e/Projects/web/steam-bot/bot.js:25:10)
    at emitTwo (events.js:126:13)
    at SteamUser.emit (events.js:214:7)
    at SteamUser._handlers.(anonymous function) (/mnt/e/Projects/web/steam-bot/node_modules/steam-user/components/logon.js:310:9)
    at SteamUser._handleMessage (/mnt/e/Projects/web/steam-bot/node_modules/steam-user/components/messages.js:249:30)
    at emitThree (events.js:136:13)
```
Thanks for all your help and time. Is there any other way to contact you if I get stuck or should I ask in this thread?

**Comment by DoctorMcKay** [comment]
Why can't you just set it in the constructor?

**Comment by anupkrbid** [comment]
I can. Just wanted to know the proper way to use ``` setOptions ``` just in case I need to use it later. But thanks a lot. So any other way to contact you other than this thread?

**Comment by DoctorMcKay** [comment]
`setOptions` is supposed to work all the time, but there's a bug preventing you from changing `enablePicsCache` until after your licenses list is received (`licenses` event).

You should use https://dev.doctormckay.com for future questions and the like.
