### ISSUE TITLE
event.game_id.toNumber is not a function

### ISSUE THREAD

**Issue by xPaw** [DoctorMcKay/node-steam-user#232]
```
steam-user/components/friends.js:618
                this._emitIdEvent('groupEvent', sid, event.headline, new Date(event.event_time * 1000), event.gid.toString(), event.game_id.toNumber());
                                                                                                                                            ^

TypeError: event.game_id.toNumber is not a function
    at forEach (steam-user/components/friends.js:618:127)
    at Array.forEach (<anonymous>)
    at SteamUser.<anonymous> (steam-user/components/friends.js:601:22)
    at handlers.forEach (steam-user/components/classes/HandlerManager.js:37:12)
    at Array.forEach (<anonymous>)
    at HandlerManager.emit (steam-user/components/classes/HandlerManager.js:36:12)
    at SteamUser._handleMessage (steam-user/components/messages.js:544:24)
    at SteamUser._handleNetMessage (steam-user/components/messages.js:470:7)
    at SteamUser.processMulti (steam-user/components/messages.js:571:9)
    at SteamUser.<anonymous> (steam-user/components/messages.js:565:16)
```

**Comment by DoctorMcKay** [comment]
#228, update your module.

**Comment by xPaw** [comment]
Ah, didn't realize you updated it multiple times already, sorry!

**Comment by DoctorMcKay** [comment]
No worries!
