### ISSUE TITLE
Error in handleNetMessage

### ISSUE THREAD

**Issue by Revadike** [DoctorMcKay/node-steam-user#248]
My bot log:
```
 2019-04-16 | 15:10:49.963 | ERROR | gotSteamError                  | A Steam error has occurred: LoggedInElsewhere
 2019-04-16 | 15:11:04.737 | INFO  | refreshedGleamDB               | Successfully refreshed GleamDB
 2019-04-16 | 15:11:40.062 | ERROR | refreshSteamWebSession         | Not logged in to Steam
 2019-04-16 | 15:11:41.031 | INFO  | loggedOnSteam                  | Logged into steam as Revadike (76561198042965266)
 2019-04-16 | 15:11:42.319 | INFO  | gotSteamWallet                 | Steam wallet balance is 15,38€
 2019-04-16 | 15:11:42.323 | INFO  | gotSteamAccountLimitations     | Steam account can invite friends
 2019-04-16 | 15:11:42.328 | INFO  | gotPlayingState                | Started playing Skater Cally (920820) on this account using another logon session
 2019-04-16 | 15:11:42.329 | INFO  | gotSteamVACDetails             | Steam account has 1 VAC ban for app: Depth (274940)
 2019-04-16 | 15:11:42.322 | INFO  | gotSteamAccountLimitations     | Steam account has no limitations
 2019-04-16 | 15:11:42.439 | INFO  | gotSteamLicenses               | Steam account owns 20916 licenses
 2019-04-16 | 15:11:44.110 | INFO  | searchSteamGiftsArchive        | Searching archive page 2
 2019-04-16 | 15:11:48.071 | INFO  | signedIntoBarter               | Logged into barter.vg
 2019-04-16 | 15:11:48.073 | INFO  | startBarterMonitor             | Monitoring barter.vg for accepted trades
 2019-04-16 | 15:11:48.091 | ERROR | sellSteamItem                  | Failed to sell steam item: HTTP error 400
 2019-04-16 | 15:11:50.691 | INFO  | gotAppOwnershipCached          | This Steam account owns 284 unknown apps, 15071 games, 265 applications, 3065 demos, 2918 DLC, 305 tools, 664 media, 105 configs, 559 videos, 1 hardware and 32 series
 2019-04-16 | 15:11:48.302 | INFO  | gotAppOwnershipCached          | Got app ownership info
 2019-04-16 | 15:11:51.898 | ERROR | expiredSteamWebSession         | Steam web session expired: Not Logged In
 2019-04-16 | 15:11:51.899 | ERROR | refreshSteamWebSession         | Not logged in to Steam
 2019-04-16 | 15:11:52.779 | INFO  | loggedOnSteam                  | Logged into steam as Revadike (76561198042965266)
 2019-04-16 | 15:11:52.960 | ERROR | crashBot                       | Fatal error: TypeError: Cannot read property 'toString' of null
    at SteamUser._handleNetMessage (node_modules\steam-user\components\messages.js:463:38)
    at TCPConnection._readMessage (node_modules\steam-user\components\connection_protocols\tcp.js:193:12)
    at Socket.emit (events.js:182:13)
    at emitReadable_ (_stream_readable.js:534:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
 2019-04-16 | 15:11:52.963 | INFO  | exitBot                        | Logging off and shutting down
```

`LoggedInElsewhere` happened because I started playing another game myself, but I think that caused this chain of events to happen. The error is caused by `steamID` being `null`.

**Comment by Revadike** [comment]
I think this should solve it? https://github.com/DoctorMcKay/node-steam-user/pull/249
