### ISSUE TITLE
client.removeFriend error

### ISSUE THREAD

**Issue by nhatkun** [DoctorMcKay/node-steam-user#253]
## Describe the bug
When use it show Error: 
```
    client.on("loggedOn",function(details) {
        client.removeFriend(["76561198089XXXXXX"]);
    });
```
## Versions
steam-user@4.8.0
node --version v10.15.3

## Screenshots and Error Logs
```
\node_modules\steam-user\components\friends.js:58
        this._send(SteamUser.EMsg.ClientRemoveFriend, {"friendid": steamID.getSteamID64()});
                                                                           ^

TypeError: steamID.getSteamID64 is not a function
    at SteamUser.removeFriend (C:\BotPROMPT\node_modules\steam-user\components\friends.js:58:69)
    at SteamUser.<anonymous> (C:\BotPROMPT\f1.js:51:16)
    at SteamUser.emit (events.js:189:13)
    at SteamUser.<anonymous> (C:\BotPROMPT\node_modules\steam-user\components\logon.js:397:9)
    at handlers.forEach (C:\BotPROMPT\node_modules\steam-user\components\classes\HandlerManager.js:37:12)
    at Array.forEach (<anonymous>)
    at HandlerManager.emit (C:\BotPROMPT\node_modules\steam-user\components\classes\HandlerManager.js:36:12)
    at SteamUser._handleMessage (C:\BotPROMPT\node_modules\steam-user\components\messages.js:532:24)
    at SteamUser._handleNetMessage (C:\BotPROMPT\node_modules\steam-user\components\messages.js:467:7)
    at SteamUser.processMulti (C:\BotPROMPT\node_modules\steam-user\components\messages.js:559:9)
```

**Comment by DoctorMcKay** [comment]
removeFriend does not accept an array. Get rid of the brackets.
