### ISSUE TITLE
TypeError: Cannot read property 'type' of null

### ISSUE THREAD

**Issue by Slydelix** [DoctorMcKay/node-steam-user#269]
## Describe the bug
Occurs sometimes when connecting to Steam

> TypeError: Cannot read property 'type' of null
    at SteamUser.<anonymous> (C:\\{Path}\node_modules\steam-user\components\logon.js:398:21)
    at handlers.forEach (C:\\{Path}\node_modules\steam-user\components\classes\HandlerManager.js:37:12)
    at Array.forEach (<anonymous>)
    at HandlerManager.emit (C:\\{Path}\node_modules\steam-user\components\classes\HandlerManager.js:36:12)
    at SteamUser._handleMessage (C:\\{Path}\node_modules\steam-user\components\messages.js:543:24)
    at SteamUser._handleNetMessage (C:\\{Path}\node_modules\steam-user\components\messages.js:478:7)
    at SteamUser.processMulti (C:\\{Path}\node_modules\steam-user\components\messages.js:570:9)
    at Gunzip.Zlib.gunzip [as cb] (C:\\{Path}\node_modules\steam-user\components\messages.js:561:17)
    at Gunzip.zlibBufferOnEnd (zlib.js:123:10)
    at Gunzip.emit (events.js:194:15)

## Versions
Node: 10.15.3
Module: 4.12.2

**Comment by DoctorMcKay** [comment]
Hm. Interesting. Looks like this would happen if you successfully log on, but Steam doesn't set your SteamID in the header of the response message. No idea why that would happen, but I'll add a workaround to avoid it crashing.

**Comment by Slydelix** [comment]
Thank you!
