### ISSUE TITLE
Cannot read property 'setTimeout' of undefined

### ISSUE THREAD

**Issue by Slydelix** [DoctorMcKay/node-steam-user#274]
## Describe the bug
Not sure what triggers it exactly but it started happening 20 minutes ago and the code hasn't been changed for months

## Versions
What version of the module and what version of Node.js are you using?
Node: v10.15.3
Module: 4.12.4

## Screenshots and Error Logs

> TypeError: Cannot read property 'setTimeout' of undefined
    at SteamUser.<anonymous> (C:\stuff\node_modules\steam-user\components\connection.js:43:26)
    at handlers.forEach (C:\stuff\node_modules\steam-user\components\classes\HandlerManager.js:37:12)
    at Array.forEach (<anonymous>)
    at HandlerManager.emit (C:\stuff\node_modules\steam-user\components\classes\HandlerManager.js:36:12)
    at SteamUser._handleMessage (C:\stuff\node_modules\steam-user\components\messages.js:543:24)
    at SteamUser._handleNetMessage (C:\stuff\node_modules\steam-user\components\messages.js:478:7)
    at TCPConnection._readMessage (C:\stuff\node_modules\steam-user\components\connection_protocols\tcp.js:193:12)
    at Socket.emit (events.js:189:13)
    at emitReadable_ (_stream_readable.js:535:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

Edit: Steam appears to be down

**Comment by Jvery** [comment]
Happens sometimes even when steam isn't lagging. If you will find how to fix it please share

**Comment by 2cab** [comment]
same thing dont know what to do

**Comment by itsjfx** [comment]
Seem to get this a lot also, any idea for a fix? What are the potential implications of removing this timeout? Seems like a rough one to debug...

**Comment by itsjfx** [comment]
Could this be replaced with ```process.nextTick``` instead?

**Comment by itsjfx** [comment]
Getting this error frequently... struggling to figure out when stream would be undefined but this._connection would be defined. 

My best theory is that when _doConnection() is called we can see this._connection is replaced with a new instance. Maybe there's a little race condition where this ```ChannelEncryptRequest``` message block is run (perhaps from a previous login?) before a socket (this._connection.stream) is built, resulting in it being undefined.
https://github.com/DoctorMcKay/node-steam-user/blob/39f0f64c0dc189be386e2e3b423bc6ccfa8b6cac/components/logon.js#L222-L248

_doConnection() is called around the codebase a few times so it's not a rare thing to run.

WebSocket code requires pings to be completed across the CM's which results in a delay for this._connection.stream being defined - maybe the cause is here.
https://github.com/DoctorMcKay/node-steam-user/blob/69155e9bbbcb826487af2cf85b15a7c722e6bbe1/components/connection_protocols/websocket.js#L37-L71

_chooseAndConnect() makes the WebSocket connection

For the TCP code the stream property is defined in the constructor so I find it very unlikely that it could be occurring in the TCP code.

**Comment by itsjfx** [comment]
A potential solution could be a simple return if the socket does not exist?
