### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by 2cab** [DoctorMcKay/node-steam-user#290]
`if (this.steamID.type == SteamID.Type.INDIVIDUAL) {
                                         ^

TypeError: Cannot read property 'type' of null
    at SteamUser.<anonymous> (C:\Users\serbe\Downloads\bot\node_modules\steam-user\components\logon.js:405:21)
    at C:\Users\serbe\Downloads\bot\node_modules\steam-user\components\classes\HandlerManager.js:37:12
    at Array.forEach (<anonymous>)
    at HandlerManager.emit (C:\Users\serbe\Downloads\bot\node_modules\steam-user\components\classes\HandlerManager.js:36:12)
    at SteamUser._handleMessage (C:\Users\serbe\Downloads\bot\node_modules\steam-user\components\messages.js:545:24)
    at SteamUser._handleNetMessage (C:\Users\serbe\Downloads\bot\node_modules\steam-user\components\messages.js:480:7)
    at SteamUser.processMulti (C:\Users\serbe\Downloads\bot\node_modules\steam-user\components\messages.js:572:9)
    at Gunzip.cb (C:\Users\serbe\Downloads\bot\node_modules\steam-user\components\messages.js:563:17)
    at Gunzip.zlibBufferOnEnd (zlib.js:149:10)
    at Gunzip.emit (events.js:323:22)`

**Comment by DoctorMcKay** [comment]
Please show your code.

**Comment by 2cab** [comment]
Cmd code or the code that I'm using with node.js

**Comment by DoctorMcKay** [comment]
Both.
