### ISSUE TITLE
Error: Request timed out in @doctormckay/stdlib

### ISSUE THREAD

**Issue by T1MOXA** [DoctorMcKay/node-steam-user#312]
## Describe the bug
These errors appear every two minutes after login.

## Versions
Module - 4.15.4,
Node - v14.3.0

## Screenshots and Error Logs
 ```
Error: Request timed out
     at Timeout._onTimeout (/bot/node_modules/@doctormckay/stdlib/components/promises.js:17:12)
     at listOnTimeout (internal/timers.js:549:17)
     at processTimers (internal/timers.js:492:7)
```

**Comment by DoctorMcKay** [comment]
What is your code doing?

**Comment by DoctorMcKay** [comment]
Nevermind, I found the cause.
