### ISSUE TITLE
File reading bug.

### ISSUE THREAD

**Issue by RobertSkonieczny** [DoctorMcKay/node-steam-user#348]
## Describe the bug
Working on rewriting my open source project and getting this strange file reading bug. Unsure if it because I am using ES6 syntax possibly?

## Versions
Using Node v14.15.1
Using ES6 Syntax
package.json - https://pastebin.com/1yqNPBFK

## Screenshots and Error Logs
PS C:\Users\Robbie\Documents\GitHub\node-steam-trade-farm> node bot
internal/fs/utils.js:781
  throw new ERR_INVALID_ARG_TYPE(
  ^

    at Object.writeFile (fs.js:1436:5)
    at FileStorage.saveFile.FileStorage.writeFile (C:\Users\Robbie\Documents\GitHub\node-steam-trade-farm\node_modules\file-manager\index.js:68:5)
    at SteamUser._handlers.<computed> (C:\Users\Robbie\Documents\GitHub\node-steam-trade-farm\node_modules\steam-user\components\logon.js:294:18)
    at SteamUser._handleMessage (C:\Users\Robbie\Documents\GitHub\node-steam-trade-farm\node_modules\steam-user\components\messages.js:216:29)
    at CMClient.emit (events.js:315:20)
    at CMClient._netMsgReceived (C:\Users\Robbie\Documents\GitHub\node-steam-trade-farm\node_modules\steam-client\lib\cm_client.js:323:8)
    at CMClient.handlers.<computed> (C:\Users\Robbie\Documents\GitHub\node-steam-trade-farm\node_modules\steam-client\lib\cm_client.js:609:8)
    at CMClient._netMsgReceived (C:\Users\Robbie\Documents\GitHub\node-steam-trade-farm\node_modules\steam-client\lib\cm_client.js:305:24)
    at TCPConnection.emit (events.js:315:20)
    at TCPConnection._readPacket (C:\Users\Robbie\Documents\GitHub\node-steam-trade-farm\node_modules\steam-client\lib\tcp_connection.js:183:7) {
  code: 'ERR_INVALID_ARG_TYPE'
}

**Comment by DoctorMcKay** [comment]
The latest v3 release was [over two years ago now](https://github.com/DoctorMcKay/node-steam-user/releases/tag/v3.29.3). Please try updating to v4.

Everything you need to know about updating to v4 is listed [in the v4 release notes](https://github.com/DoctorMcKay/node-steam-user/releases/tag/v4.0.0).
