### ISSUE TITLE
Weird issue/bug

### ISSUE THREAD

**Issue by Papzi** [DoctorMcKay/node-steam-user#4]
I dont know why but at very random moments this error occurs and it doesnt trace back to my code but to some code from steam-user and steam. Is it something i have done wrong before in my code? I hope you can fix this or tell what i have done wrong :D
```
debug: 'Unhandled message: 7503'
debug: 'Unhandled message: 1'
debug: 'Handled message: 5427'
debug: 'Unhandled message: 1'
debug: 'Handled message: 5578'
D:\Local Disk E\somewhere\node_modules\steam-user\node_modules\bytebuffer\dist\ByteBufferNB.js:1800
               throw RangeError("Index out of range: "+offset+" <= "+this.buff
                                                                    ^
RangeError: Index out of range: 20 <= 20
    at RangeError (native)
    at module.exports.ByteBufferPrototype.readCString (D:\Local Disk E\somewhere\node_modules\steam-user\node_modules\bytebuffer\dist\ByteBufferNB.js:1800:70)
    at SteamUser._handlers.(anonymous function) (D:\Local Disk E\somewhere\node_modules\steam-user\components\chat.js:294:29)
    at SteamUser._handleMessage (D:\Local Disk E\somewhere\node_modules\steam-user\components\messages.js:157:29)
    at SteamClient.emit (events.js:129:20)
    at SteamClient._netMsgReceived (D:\Local Disk E\somewhere\node_modules\steam\lib\steam_client.js:182:10)
    at SteamClient.handlers.(anonymous function) (D:\Local Disk E\somewhere\node_modules\steam\lib\steam_client.js:269:10)
    at SteamClient._netMsgReceived (D:\Local Disk E\somewhere\node_modules\steam\lib\steam_client.js:167:26)
    at Connection.emit (events.js:107:17)
    at Connection._readPacket (D:\Local Disk E\somewhere\node_modules\steam\lib\connection.js:50:8)
```
EDIT: the debug messages you see is from `steamUser.on("debug",function ...`

EDIT 2: I just investigated a bit more and found out that it always happens at this debug message:
`debug: 'Handled message: 5578'` when it calls ByteBufferPrototype.readCString from bytebufferNB.

EDIT 3: Im pretty sure that it is the `'Handled message: 5578'` that's causing the crash since if i add this code: `if (msgName == "5578") { return; }` at Line 156 at "steam-user/components/messages.js" then it doesn't crash. I dont know what msgName 5578 is so this is not a fix just a temporary work around.

**Comment by DoctorMcKay** [comment]
Just as a guess, does it crash when you start typing a chat message while logged into the same account as the bot?

**Comment by Papzi** [comment]
@DoctorMcKay Yes it does.
