### ISSUE TITLE
time out v2 - updated npm

### ISSUE THREAD

**Issue by wickedroid** [DoctorMcKay/node-steam-user#425]
Error: Request timed out
    at Promises.timeoutPromise (/home/w/node_modules/@doctormckay/stdlib/components/promises.js:12:12)
    at Promises.timeoutCallbackPromise (/home/w/node_modules/@doctormckay/stdlib/components/promises.js:87:25)
    at SteamUser.activateAuthSessionTickets (/home/w/node_modules/steam-user/components/appauth.js:175:26)
    at buildToken (/home/w/node_modules/steam-user/components/appauth.js:122:17)
    at /home/w/node_modules/steam-user/components/appauth.js:128:6
    at Immediate.<anonymous> (/home/w/node_modules/@doctormckay/stdlib/components/promises.js:94:6)
    at process.processImmediate (node:internal/timers:476:21)
Node.js v18.14.2

**Comment by DoctorMcKay** [comment]
Show the code where you're calling activateAuthSessionTickets
