### ISSUE TITLE
getManifestAsync returns 404

### ISSUE THREAD

**Issue by antal-k** [DoctorMcKay/node-steam-user#442]
## Describe the bug
Calling this function returns 404, probably related to steam changes

## Versions
4.28.5, node 18

## Screenshots and Error Logs
```
(node:60848) [steam-user] Warning: No branch name was specified for app 730, depot 731. Assuming "public".
(Use `node --trace-warnings ...` to show where the warning was created)

node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^
OperationalError: HTTP error 404
    at ClientRequest.<anonymous> (/Users/-/melo/-/stickers/node_modules/steam-user/components/cdn.js:585:13)
    ... 9 lines matching cause stack trace ...
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  cause: Error: HTTP error 404
      at ClientRequest.<anonymous> (/Users/-/melo/-/stickers/node_modules/steam-user/components/cdn.js:585:13)
      at Object.onceWrapper (node:events:628:26)
      at ClientRequest.emit (node:events:513:28)
      at HTTPParser.parserOnIncomingClient (node:_http_client:701:27)
      at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
      at Socket.socketOnData (node:_http_client:542:22)
      at Socket.emit (node:events:513:28)
      at addChunk (node:internal/streams/readable:324:12)
      at readableAddChunk (node:internal/streams/readable:297:9)
      at Readable.push (node:internal/streams/readable:234:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23),
  isOperational: true
}
```

**Comment by DoctorMcKay** [comment]
getManifestAsync is not a function provided by steam-user.

**Comment by antal-k** [comment]
You are right, its `getManifest` with promisify.

**Comment by DoctorMcKay** [comment]
Why are you using promisify? Everything in steam-user already supports promises.

**Comment by antal-k** [comment]
It's not really me, I trying to use https://github.com/Step7750/node-csgo-cdn and getting this error. i think it was created years ago, but worked well a month ago.

**Comment by wavpro** [comment]
I'm currently dealing with the same node-csgo-cdn issue, and I'm trying to debug it. In this object:
```js
{
      gid: '4463297689470707294',
      size: '32716117888',
      download: '13643537264'
}```
`gid` is the correct manifestId, right? I'm hoping you can answer this, sorry for the ping @DoctorMcKay

node-csgo-cdn supplies the whole object shown above to the getManifest function, where it is strictly specified that it is a string that is required.

I tried to change it to supply the gid, but I just get a `401 Unauthorized` error, on this public manifest (CSGO, depot id 731, public). Do you know why this could happen, if `gid` is the correct value for manifestId?

**Comment by DoctorMcKay** [comment]
node-csgo-cdn does need to be updated for the new way of retrieving manifest IDs, but [4.28.6](https://github.com/DoctorMcKay/node-steam-user/releases/tag/v4.28.6) adds a shim (with a warning) if you pass in an object with a `gid` key.
