### ISSUE TITLE
SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by farmer1234** [DoctorMcKay/node-steam-user#479]
Error:
/root/xx/.../.../.../node_modules/steam-user/components/03-messages.js:740
                                machineId: this._logOnDetails?.machine_id
                                                              ^
SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/root/xx/.../.../.../node_modules/steam-user/components/content_manifest.js:4:27)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    
Problematic line:
'machineId: this._logOnDetails?.machine_id' of (/node_modules/steam-user/components/03-messages.js'.)

Fix:
machineId: this._logOnDetails && this._logOnDetails.machine_id

My question is, by using the line suggested in the 'Fix' is my code prone to any vulnerabilities or is it just fine. If it is, what are the other solutions available?

**Comment by DoctorMcKay** [comment]
Update your Node.js to 14.0.0 or later, as specified in the readme.
