### ISSUE TITLE
Logon error

### ISSUE THREAD

**Issue by luucdev** [DoctorMcKay/node-steam-user#70]
I sporadically get this error whenever I try to logon, causing my whole Node app to crash:

```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: InvalidPassword
    at SteamUser._handlers.(anonymous function) (D:\Documents\Jackpot Node.js Bot\web\luuc-jackpot\node_modules\steam-user\components\logon.js:297:16)
    at SteamUser._handleMessage (D:\Documents\Jackpot Node.js Bot\web\luuc-jackpot\node_modules\steam-user\components\messages.js:184:29)
    at emitThree (events.js:97:13)
    at CMClient.emit (events.js:175:7)
    at CMClient._netMsgReceived (D:\Documents\Jackpot Node.js Bot\web\luuc-jackpot\node_modules\steam-user\node_modules\steam-client\lib\cm_client.js:260:8)
    at CMClient.handlers.(anonymous function) (D:\Documents\Jackpot Node.js Bot\web\luuc-jackpot\node_modules\steam-user\node_modules\steam-client\lib\cm_client.js:358:8)
    at CMClient._netMsgReceived (D:\Documents\Jackpot Node.js Bot\web\luuc-jackpot\node_modules\steam-user\node_modules\steam-client\lib\cm_client.js:242:24)
    at emitOne (events.js:77:13)
    at TCPConnection.emit (events.js:169:7)
    at TCPConnection._readPacket (D:\Documents\Jackpot Node.js Bot\web\luuc-jackpot\node_modules\steam-user\node_modules\steam-client\lib\tcp_connection.js:59:7)
```

**Comment by DoctorMcKay** [comment]
Every `EventEmitter` in node will crash your application if it emits an `error` event that isn't being listened for. Listen for the `error` event.

Steam can send back fake `InvalidPassword` errors when it's down, or when you've made too many logins from your IP in a short time.

**Comment by nihal12345** [comment]
How would i listen to these error events using try catch??

**Comment by DoctorMcKay** [comment]
You wouldn't. You would attach an event listener to the `error` event.
