### ISSUE TITLE
Rate Limit Exceeded? 

### ISSUE THREAD

**Issue by rycao18** [DoctorMcKay/node-steam-user#75]
What is this? 

```
error:  Error: RateLimitExceeded
    at SteamUser._handlers.(anonymous function) (C:\Users\Richard\Desktop\Steam\NodeJS\CombinedBot\node_modules\steam-user\components\logon.js:320:16)
    at SteamUser._handleMessage (C:\Users\Richard\Desktop\Steam\NodeJS\CombinedBot\node_modules\steam-user\components\messages.js:198:29)
    at emitThree (events.js:102:20)
    at CMClient.emit (events.js:175:7)
    at CMClient._netMsgReceived (C:\Users\Richard\Desktop\Steam\NodeJS\CombinedBot\node_modules\steam-user\node_modules\steam-client\lib\cm_client.js:278:8)
    at CMClient.handlers.(anonymous function) (C:\Users\Richard\Desktop\Steam\NodeJS\CombinedBot\node_modules\steam-user\node_modules\steam-client\lib\cm_client.js:386:8)
    at CMClient._netMsgReceived (C:\Users\Richard\Desktop\Steam\NodeJS\CombinedBot\node_modules\steam-user\node_modules\steam-client\lib\cm_client.js:260:24)
    at emitOne (events.js:77:13)
    at TCPConnection.emit (events.js:169:7)
    at TCPConnection._readPacket (C:\Users\Richard\Desktop\Steam\NodeJS\CombinedBot\node_modules\steam-user\node_modules\steam-client\lib\tcp_connection.js:73:7)
```

How do I get around this?

**Comment by DoctorMcKay** [comment]
You:

a) start reading the readme which clearly states where you should ask such questions, and

b) stop exceeding the rate limit

**Comment by dogusev** [comment]
https://www.reddit.com/r/SteamBot/wiki/rate-limits
