### ISSUE TITLE
Can't change name to Unicode characters

### ISSUE THREAD

**Issue by Robinlemon** [DoctorMcKay/node-steam-user#78]
When using `client.setPersona(looking to trade, 'Some fancy name here');` it fails to update the name if using Unicode characters; how can I work around this? As you can use the same Unicode characters when changing the bots name through the steam client; I thought this was weird behaviour as they all use the same http requests (As far as I know).

EDIT: I've also tried the node-steamcommunity module,

```
BOT.COMMUNITY.editProfile({
    name: '𝓐𝓫𝓬𝓭𝓮𝓕𝓰𝓱𝓲𝓳𝓚𝓛 𝓜𝓝𝓞  ' + BOT.ID),
    primaryGroup: '0123456789'
}, function(err){
    if(err) console.log(err);
});
```

This changes the name, although only to 𝓐𝓫𝓬𝓭𝓮𝓕𝓰𝓱 (The first 8 characters), I believe this is because each Unicode character takes 2 spaces instead of one. I'm also receiving this error:

```
Error: Bad location specified.Failed to set new primary group.
    at SteamCommunity.<anonymous> (F:\oo\node_modules\steamcommunity\components\profile.js:136:16)
    at Request._callback (F:\oo\node_modules\steamcommunity\components\http.js:67:15)
    at Request.self.callback (F:\oo\node_modules\request\request.js:198:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (F:\oo\node_modules\request\request.js:1035:10)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at Gunzip.<anonymous> (F:\oo\node_modules\request\request.js:962:12)
    at emitNone (events.js:91:20)
    at Gunzip.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:934:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

The group ID is the Steam64ID of the group, I'm also receiving this error:

```
{ Error: HTTP error 429
    at SteamCommunity._checkHttpError (F:\oo\node_modules\steamcommunity\components\http.js:108:9)
    at Request._callback (F:\oo\node_modules\steamcommunity\components\http.js:50:61)
    at Request.self.callback (F:\oo\node_modules\request\request.js:198:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (F:\oo\node_modules\request\request.js:1035:10)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (F:\oo\node_modules\request\request.js:962:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:934:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9) code: 429 }
```

NOTE: I can set my name to 𝓐𝓫𝓬𝓭𝓮𝓕𝓰𝓱𝓲𝓳𝓚𝓛 𝓜𝓝𝓞 in the Steam client, is the length limited in the module?

**Comment by gekkedev** [comment]
Not sure if this is the root of the problem, but your code sample has more closing brackets than opening ones.

**Comment by Robinlemon** [comment]
> Not sure if this is the root of the problem, but your code sample has more closing brackets than opening ones.

That is not even true.

**Comment by gekkedev** [comment]
Try pasting the snippet into a [syntax checker](https://jshint.com/) 😉 
```
Six warnings
--
2 | Expected '}' to match '{' from line 1 and instead saw ')'.
3 | Expected ')' and instead saw ':'.
3 | Missing semicolon.
3 | Expected an assignment or function call and instead saw an expression.
3 | Missing semicolon.
3 | Unrecoverable syntax error. (50% scanned).
```

**Comment by Robinlemon** [comment]
@gekkedev My bad, this is still unrelated to the issue though. It was a different implementation in my software and when producing the demo I forgot to remove a closing bracket.

**Comment by DoctorMcKay** [comment]
Sorry I took so long to look at this, but it seems to work fine for me.

```js
client.setPersona(SteamUser.EPersonaState.Online, "𝓐𝓫𝓬𝓭𝓮𝓕𝓰𝓱𝓲𝓳𝓚𝓛 𝓜𝓝𝓞");
```

![](https://mckay.media/r2Z5b.png)

**Comment by Robinlemon** [comment]
Perhaps that is the case as I cannot seem to replicate the issue anymore.

 I originally added you the other day to ask if you’d support a PR for typescript declarations though.
