### ISSUE TITLE
Login fail, Steam.EResult.Fail (2)

### ISSUE THREAD

**Issue by tambu22** [DoctorMcKay/node-steam-user#81]
i really dont think that im doing something worng

```js
var fs     = require('fs');
var Steam            = require('steam');
var SteamWebLogOn    = require('steam-weblogon');
var SteamTotp = require('steam-totp');
var SteamC = require('steam-client');
var steamClient = new SteamC.CMClient();
var SteamU=require("steam-user");
var steamUser = new SteamU();
var steamWebLogOn = new SteamWebLogOn(steamClient, steamUser);
steamClient.connect(); // connect to the Steam network
steamClient.on('connected', function() 
{
    console.log("Steam: Connected");
    var code = SteamTotp.generateAuthCode('secret=');
    steamUser.logOn({
        accountName: 'user', // your login name
        password: 'pw', // your login password
        twoFactorCode: code
    }); // login to Steam
});
steamClient.on('logOnResponse', function(logonResp) 
{
    for (var ind in Steam.EResult)
     {
         if (Steam.EResult[ind]===logonResp.eresult)
         {
            console.log(ind);
            break;
         }
     }
    if (logonResp.eresult == Steam.EResult.OK) {  
    }
});
steamClient.on('servers', function(servers) 
{
    fs.writeFile('servers', JSON.stringify(servers));
});
```

i see this on console (takes like 1-2 mins trying to connect before giving Steam.EResult.Fail)

```
Steam: Connected
Fail
events.js:154
      throw er; // Unhandled 'error' event
      ^
Error: Disconnected
    at CMClient._disconnected (/MY_DIR/node_modules/steam-client/lib/cm_client.js:294:22)
    at emitOne (events.js:90:13)
    at TCPConnection.emit (events.js:182:7)
    at TCP._onclose (net.js:477:12)
```

**Comment by DoctorMcKay** [comment]
**Please direct future questions to the [dedicated forum](https://dev.doctormckay.com/forum/7-node-steam-user/).**

Try not connecting first, just call logOn.

**Comment by tambu22** [comment]
i found the error:
on line

`var steamUser = new SteamU();`

the correct is: 

`var steamUser = new SteamU(steamClient);`

anyways now im trying to modify the fetch confirmations metod to allow set the public ip that it use 
tnks, you always here :)
