### ISSUE TITLE
Error thrown during object instansiation 

### ISSUE THREAD

**Issue by Xetrics** [DoctorMcKay/node-steam-user#97]
```
/home/xetrics/steamauth/node_modules/steam/lib/handlers/user/index.js:10
  this._client.on('message', function(header, body, callback) {
              ^
TypeError: Cannot read property 'on' of undefined
    at new SteamUser (/home/xetrics/steamauth/node_modules/steam/lib/handlers/user/index.js:10:15)
    at Object.<anonymous> (/home/xetrics/steamauth/confo.js:15:14)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:422:7)
    at startup (bootstrap_node.js:143:9)
```

This is thrown when I do
```
const SteamUser = require("node-steam-user");
const user = new SteamUser();
```

**Comment by DoctorMcKay** [comment]
The npm name is `steam-user`, not `node-steam-user`.

**Comment by Xetrics** [comment]
It happens when using the base steam package as well, I will open an issue there.
